# packages in environment at C:\Users\Casey\scoop\apps\miniconda3\current\envs\instapy:
#
# Name                    Version                   Build  Channel
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
beautifulsoup4            4.9.1            py38h32f6830_0    conda-forge
brotlipy                  0.7.0           py38h1e8a9f7_1000    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py38h32f6830_0    conda-forge
cffi                      1.14.0           py38ha419a9e_0    conda-forge
chardet                   3.0.4           py38h32f6830_1006    conda-forge
clarifai                  2.6.2                    pypi_0    pypi
colorama                  0.4.3                      py_0    conda-forge
configparser              5.0.0                    pypi_0    pypi
cryptography              2.9.2            py38hba49e27_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
easyprocess               0.3                      pypi_0    pypi
emoji                     0.5.4                    pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
geckodriver               0.26.0               he025d50_0    conda-forge
googleapis-common-protos  1.52.0                   pypi_0    pypi
grpcio                    1.30.0           py38h735fc1f_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
instapy                   0.6.9                    pypi_0    pypi
ipykernel                 5.3.2            py38h5ca1d4c_0    conda-forge
ipython                   7.16.1           py38h23f93f0_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.17.1           py38h32f6830_0    conda-forge
jsonschema                2.6.0                    pypi_0    pypi
jupyter_client            6.1.6                      py_0    conda-forge
jupyter_core              4.6.3            py38h32f6830_1    conda-forge
libsodium                 1.0.17               h2fa13f4_0    conda-forge
meaningcloud-python       1.2.2                    pypi_0    pypi
openssl                   1.1.1g               he774522_0    conda-forge
parso                     0.7.0              pyh9f0ad1d_0    conda-forge
pickleshare               0.7.5           py38h32f6830_1001    conda-forge
pip                       20.1.1                     py_1    conda-forge
plyer                     1.4.3                    pypi_0    pypi
prompt-toolkit            3.0.5                      py_1    conda-forge
protobuf                  3.12.2                   pypi_0    pypi
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pysocks                   1.7.1            py38h32f6830_1    conda-forge
python                    3.8.4           cpython_h5fd99cc_0    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-telegram-bot       12.8                     pypi_0    pypi
python_abi                3.8                      1_cp38    conda-forge
pywin32                   227              py38hfa6e2cd_0    conda-forge
pyyaml                    5.3.1                    pypi_0    pypi
pyzmq                     19.0.1           py38h77b9d75_0    conda-forge
regex                     2020.7.14        py38h1e8a9f7_0    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
selenium                  3.141.0         py38h9de7a3e_1001    conda-forge
setuptools                49.2.0           py38h32f6830_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
soupsieve                 2.0.1            py38h32f6830_0    conda-forge
sqlite                    3.32.3               he774522_1    conda-forge
tornado                   6.0.4            py38hfa6e2cd_0    conda-forge
tqdm                      4.48.0             pyh9f0ad1d_0    conda-forge
traitlets                 4.3.3            py38h32f6830_1    conda-forge
urllib3                   1.25.9                     py_0    conda-forge
vc                        14.1                 h21ff451_3  
vs2015_runtime            15.5.2                        3  
wcwidth                   0.2.5              pyh9f0ad1d_0    conda-forge
webdriverdownloader       1.1.0.3                  pypi_0    pypi
wheel                     0.34.2                     py_1    conda-forge
win_inet_pton             1.1.0                    py38_0    conda-forge
wincertstore              0.2                   py38_1003    conda-forge
zeromq                    4.3.2                ha925a31_3    conda-forge
zlib                      1.2.11            h2fa13f4_1006    conda-forge
